### ISSUE TITLE
Convert `ObjectPair` and `(String, OwnedObject)` into `Accessible`s.

### ISSUE THREAD

**Issue by luukvanderduim** [odilia-app/atspi#107]
As a library, we want uniform and unambiguous typing to avoid confusion and errors for users and maintainers.

In `atspi` we find `ObjectPair`s, `Accessible`s, and `(String, zvariant::OwnedObject)` tuples which are different representations of the same data.

`ObjectPair` is an alias for `(String, zvariant::OwnedObject)`.

`Accessible` has this form:

```rust
#[derive(Debug, Clone, Serialize, Deserialize, Type, PartialEq, Eq, Hash)]
pub struct Accessible {
	pub name: OwnedUniqueName,
	pub path: OwnedObjectPath,
}
```

In the context of `atspi` we want these to all become `Accessible`'s as that describes their purpose within this domain best.

**Comment by TTWNO** [comment]
I'd actually argue that `Accessible` should change its `name` type to `String`, since that's the type sent over the bus.

**Comment by luukvanderduim** [comment]
We know this string to be the bus name. 
I prefer the strongest type we can deserialize to, if we can guarantee it should in all cases.

For example:
Would a `UniqueName` support an empty string?

Toolkits using `at-spi-adaptor` will return the empty string with a `null` `ObjectPath` when calling `Accessible::get_parent` on the root node.
So if it does not, we must fallback to strings.
