### ISSUE TITLE
Match signatures with XML with tests

### ISSUE THREAD

**Issue by TTWNO** [odilia-app/atspi#125]
As [Federico mentions in his GAUDEC talk](https://www.youtube.com/live/WVWrllJQJ_s?feature=share&t=4581) we should be matching the signature of our various types directly with the XML.

```rust
assert_eq!(
    MyType::signature(),
    signature_from("Cache.xml", "MySignal"),
);
```

**Comment by luukvanderduim** [comment]
Working on it.
