### ISSUE TITLE
Consider renaming `Accessible` to `ObjectReference`

### ISSUE THREAD

**Issue by TTWNO** [odilia-app/atspi#126]
"Accessible" does not really make sense as a name. In [Federico's GAUDEC talk](https://www.youtube.com/live/WVWrllJQJ_s?feature=share&t=4493) he shows an example of a complex structure and names these all "ObjectReference", which is much more clear and useful to newcomers and still paints the right idea.

This also allows us to get rid of the distinction between an object that implements accessible "Accessible which implements the accessible interface", and then we could write the unambiguous "object which implements the accessible interface".

**Comment by luukvanderduim** [comment]
Yeah i noticed `ObjectReference` too in the slides. I agree that it is important to avoid confusion between type and trait, but I disagree that `Accessible` did not make sense - even in the worst light `Accessible` gives hints to purpose and contextual provenance of the objects referred to, all in one word. A work of art. But I guess I am partial. :smile: 
 
What I like about `ObjectReference` is that it functionally describes what these things are but what I like less is that it does so in the most generic way. Is it the best we can do? Maybe boring is good.
And should we be worried that it is possible to be confused over 'reference'?

**Comment by TTWNO** [comment]
As long as "reference" is defined in the documentation, it should be fairly clear.
