### ISSUE TITLE
`::expect` does not format.

### ISSUE THREAD

**Issue by luukvanderduim** [odilia-app/atspi#156]
In the code base we can find multiple occurrences of eg.:

```Rust
let serde_val = serde_plain::to_string(&iface).expect("Unable to serialize {iface}");
```
or

```Rust
let encoded = to_bytes(ctxt, &from_role).expect("Unable to encode {from_role}");
```
However, `.expect()` does not support inserting and formatting variables.
Also, inclusion of `{err}` is unnecessary because `expect` will append the error automatically:

See: [playground example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1760b04ecd037ea9c112383a99546ae8)

And the [std rust docs on `Result::expect`](https://doc.rust-lang.org/stable/std/result/enum.Result.html#method.expect)

## "What were they thinking?"

Note the guidelines on the message itself in the link above.
The expect message should contain the reason or assumption why we expect `Result::Ok()`. 

Could we adopt this guidance, to help us or future developers, as when debugging it may help to learn about the rationale why we thought - at time of writing - this was okay.

Thoughts?

**Comment by TTWNO** [comment]
Interestingly, there is no clippy lint for this, but [there is a proposal for one](https://github.com/rust-lang/rust-clippy/issues/10195).
