### ISSUE TITLE
Add example for getting the accessibility tree

### ISSUE THREAD

**Issue by C-Loftus** [odilia-app/atspi#173]
I believe that getting the accessibility tree is very important for many accessibility applications and would be helpful to show as an example. For instance, for voice based interaction there are many times where we want to annotate all the a11y elements with a label. (i.e. labeling it with a number so we can just say the number to click on it)

The only other atspi example repo on Github shows examples on dumping the tree so I think there is precedent that this is a useful example to show
 https://github.com/infapi00/at-spi2-examples

**Comment by TTWNO** [comment]
Fixed by #188
