### ISSUE TITLE
Rename `BusProperties::build` to `BusProperties::from_message` and auto implement conversion for most User Facing Event Types.

### ISSUE THREAD

**Issue by luukvanderduim** [odilia-app/atspi#181]
Our UFETs implement `BusProperties` (`GenericEvent`) which provides: 

```Rust
	fn build(item: ObjectRef, body: Self::Body) -> Result<Self, AtspiError>
	where
		Self: Sized;
```
We define per-event how the UFET is constructed from (essentially) a `Message` because `<T as BusProperties>::build` is employed in `from_dbus_message!` only.

```Rust
StateChangedEvent::build(msg.try_into()?, msg.body().deserialize::<StateChangedEvent::Body>()?)
```
Observe that most UFETs do not even need a body, in that case the second argument in the signature is underscored `_body:`

- Rename this method `from_message`
- Define a [default implementation](https://doc.rust-lang.org/book/ch10-02-traits.html#default-implementations) for this method that does:

```Rust
// extract header from Message and:
// validate interface and member with this traits consts, then:

let item: ObjectRef = msg.try_into()?;
Ok( Self {  item } )
```
This will reduce a number of macro expansions, remove `impl_from_dbus_message`, remove how `build` eludes to a builder pattern that is not there and simplifies most conversions by not needing to define them I think.

**Comment by TTWNO** [comment]
This sounds like a great plan! Should I do it? Or would you like to?

**Comment by luukvanderduim** [comment]
You're very welcome to make this happen. It would fit nicely in your new-generic-event-trait branch.

That being said, if you feel you are somewhat overburdened, I am happy to do it. I have time this week.

**Comment by TTWNO** [comment]
All good; I got a new keyboard this week, and I need to break it in!

**Comment by TTWNO** [comment]
I think that there are some other issues that are not possible to fix due to compiler limitations. Not being able to apply a blanket implementation for `TryFrom<FORIEGN_TYPE>` is a significant issue; tho only way around is to add another `macro_rules!` that automatically implements the base case of `BusProperties` given the const identifiers.

Would that suffice?
