### ISSUE TITLE
Apparently unneeded dependency on serde_with in atspi-macros

### ISSUE THREAD

**Issue by mwcampbell** [odilia-app/atspi#40]
It looks like atspi-macros doesn't actually need the dependency on serde_with; it compiles fine without it. I bring this up because serde_with, at least using default features, adds many more dependencies, including such apparently nonsensical ones as android_system_properties (that one came indirectly via chrono). These may all be build-only, and some may be platform-specific dependencies that don't actually come up on any build platform, but some people will find the addition of so many extra dependencies in their Cargo.lock file annoying anyway.

**Comment by luukvanderduim** [comment]
Thanks for bringing this to our attention.

We actually have a few more that `cargo-udeps` considers unused: 
```Bash
unused dependencies:
`atspi-macros v0.1.2 (/atspi-macros)`
└─── dependencies
     ├─── "prettyplease"
     ├─── "serde-xml-rs"
     └─── "zbus_xmlgen"
```

@TTWNO Can I safely merge the branch that removes the unused deps?

Thanks!

**Comment by TTWNO** [comment]
Sorry, I didn't even mean to publish that code to crates.io, I'm not sure how I ended up doing that.

Should be good now.
