### ISSUE TITLE
Consider dropping the apparently-unused XML-based generation from atspi-macros

### ISSUE THREAD

**Issue by mwcampbell** [odilia-app/atspi#57]
Unless I'm missing something, it appears that the `create_from_xml` macro in atspi-macros isn't being used, in either atspi or Odilia. If that's correct, then I strongly recommend dropping that macro from this crate. Then, this crate won't need to depend on zbus and related crates. Eliminating zbus from the build-time dependencies will have a major impact on compile time, especially in release builds. If the plan was to start using `create_from_xml` later, please reconsider that plan. The number of dependencies introduced by atspi and zbus is already causing some friction in a current AccessKit integration project; I'd like to get those numbers down.

If there's no objection, I can open a PR to make the requested change.

**Comment by TTWNO** [comment]
We can remove it from the crate if you'd like, but `atspi` itselt still needs `zbus`. Does AccessKit not use `zbus` at all?

Pwrhaps I misunderstand how Accessakit is using the `atspi` crate. Could you clarify further?

**Comment by mwcampbell** [comment]
We're using zbus, and we don't have any immediate plans to change it. But depending on zbus in the atspi-macros crate apparently means that zbus and all its dependencies have to be compiled twice in a release build.

I'm curious about why `create_from_xml`, and all the functions it uses, were written and then not used.

**Comment by TTWNO** [comment]
Oh shoot! Ok, I see.

These were inrroduced back when the macro invocations were going to look like: `#[atspi_proxy("xml/Accessible.xml")]`

This ended up being moved to the `atspi-codegen` crate, which is *not* compiled with atspi.

If you can make an MR, great! If not, I'll get to it in the next few days.
