### ISSUE TITLE
Apparently unused dependencies on serde_plain and strum

### ISSUE THREAD

**Issue by mwcampbell** [odilia-app/atspi#59]
I see that atspi now depends on serde_plain and strum, but these dependencies don't seem to be used in the code. Is this a mistake, or am I missing something?

**Comment by TTWNO** [comment]
I'm very sorry about this. This appears to be an oversight on my part on a recently merged PR.

We now have a `#![deny(unused_crate_dependencies)]` in our `lib.rs`, which will prevent compilation of `atspi` when there are unused dependencies in `Cargo.toml`.

Sorry again for the inconvenience. This is my first time maintaining a major dependency, so I'm leaning new things as I go. You're pushing me to be a better maintainer! Thank you!

**Comment by TTWNO** [comment]
There's also `v0.10.1`, which removed these unused dependencies.

**Comment by mwcampbell** [comment]
No worries. Arnold and I are also learning how to maintain a library project like this. Thanks for the quick turnaround.
