### ISSUE TITLE
Many Roles return "Invalid" in its implementation of Display

### ISSUE THREAD

**Issue by wash2** [odilia-app/atspi#71]
Specifically, the Application role returns "Invalid", when it could probably return "application". I bumped into this when trying to make iced applications relying on accesskit, show up in accerciser, which requests the localized role name. https://github.com/wash2/accesskit/commit/3d079d7d4e915d2a497f16578593f50918ade1e2 

I guess some kind of method for returning a localized role name would be good?

**Comment by DataTriny** [comment]
I'm adding the missing role names. PR coming soon.

I think the atspi crate should not try to provide localized role names. These are only useful for roles defined by the application (`Role::Extended`). It is then the AT-SPI provider's responsibility to return a value if appropriate, and the atspi crate currently doesn't handle this responsibility.
