### ISSUE TITLE
Reduce dependency tree

### ISSUE THREAD

**Issue by TTWNO** [odilia-app/atspi#9]
`atspi`, in its current state, has a dependency tree in at 113 as reported by `cargo tree | grep -ve '*' | wc -l`. This `grep` is to remove lines containing existing dependencies in the tree. Basically, it ignores duplicates.

I know it's arbitrary, but I think we should try to get that down to 50 or so, maybe less. Let's find the largest libraries which we are using the least of and scrap them in favor of something simple and home-grown.

**Comment by DataTriny** [comment]
I think the following counts more accurately:

```bash
cargo tree --prefix none -e normal | grep -ve '*' | wc -l
```

It is currently at 141. I bet `zbus` brings most of the dependencies though. It's probably the one I'd be less in favor of replacing.

**Comment by TTWNO** [comment]
Partially adressed by #82
